version: '3.8'

services:
  app:
    build: ./app/
    depends_on:
      - db
    environment:
      PYTHONUNBUFFERED: 1
    networks:
      - test

  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=postgresdb
      - POSTGRES_HOST=db
    ports:
      - '5432:5432'
    networks:
      - test

  flyway:
    image: flyway/flyway:8.5.8-alpine
    command:
      -url=jdbc:postgresql://db:5432/postgresdb -user=postgres -password=root migrate
    volumes:
      - .:/flyway/sql
    depends_on:
      - db
    networks:
      - test

networks:
  test: